apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ include "watchalert.componentName" (dict "root" . "component" "service") }}
    {{- include "watchalert.labels" . | nindent 4 }}
  name: {{ include "watchalert.componentName" (dict "root" . "component" "service") }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "watchalert.componentName" (dict "root" . "component" "service") }}
  template:
    metadata:
      labels:
        app: {{ include "watchalert.componentName" (dict "root" . "component" "service") }}
        {{- include "watchalert.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.service.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.service.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      initContainers:
        - name: wait-for-mysql
          image: {{ .Values.initContainers.wait.image.repository }}:{{ .Values.initContainers.wait.image.tag }}
          command:
            - sh
            - -c
            - until nc -z -v -w 30 {{ include "watchalert.componentName" (dict "root" . "component" "mysql") }} 3306; do echo "Waiting for MySQL..."; sleep 3; done;
        - name: wait-for-redis
          image: {{ .Values.initContainers.wait.image.repository }}:{{ .Values.initContainers.wait.image.tag }}
          command:
            - sh
            - -c
            - until nc -z -v -w 30 {{ include "watchalert.componentName" (dict "root" . "component" "redis") }} 6379; do echo "Waiting for Redis..."; sleep 3; done;

      containers:
        - name: {{ include "watchalert.componentName" (dict "root" . "component" "service") }}
          image: {{ .Values.service.image.repository }}:{{ .Values.service.image.tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: 9001
              name: http
          volumeMounts:
            - name: config
              mountPath: /app/config
          env:
            - name: TZ
              value: Asia/Shanghai
          livenessProbe:
            {{- toYaml .Values.service.livenessProbe | nindent 12 }}

          readinessProbe:
            {{- toYaml .Values.service.readinessProbe | nindent 12 }}

          resources:
            {{- toYaml .Values.service.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "watchalert.componentName" (dict "root" . "component" "service-config") }}